import asyncio
from fastapi import FastAPI
from engine.marketEngine import MarketEngine
from api.routes import router, set_engine
from fastapi.middleware.cors import CORSMiddleware

engine_instance = MarketEngine()
set_engine(engine_instance) # Pass the instance to the routes file

async def simulation_loop():
    engine_instance.start() 
    while True:
        candle = engine_instance.step()
        # if len(candle):
        #     print(f"New candle generated by engine: \n{candle}")
        #     # print(candle.to_dict(orient="records"))
        await asyncio.sleep(0.5)  

app = FastAPI()
app.include_router(router) # Mounts all endpoints from routes.py

origins = [
    "http://localhost",
    "http://localhost:3000", # <-- Add your frontend development URL here
    "http://127.0.0.1:5500",    # Exact match for Live Server
    "http://localhost:5500", 
    "https://your-production-frontend.com",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
async def startup_event():
    # Start the background task using the local engine instance
    asyncio.create_task(simulation_loop())
